all:
	javac -cp C:\Java\tubesai\weka.jar MLPerceptron.java Perceptron.java

me:
	javac -cp C:\Java\tubesai\weka.jar ANN.java MLPerceptron.java Perceptron.java

run:
	java -cp .;C:\Java\tubesai\weka.jar ANN

mlp:
	java MLPerceptron

