all:
	javac -cp .;weka.jar MLPerceptron.java Perceptron.java

me:
	javac -cp .;weka.jar ANN.java MLPerceptron.java Perceptron.java

run:
	java -cp .;weka.jar ANN

mlp:
	java MLPerceptron

